### PR TITLE
Version change on top menu

### PR DESCRIPTION
**Pull request by TheLittleThings01**
Just a version change

### CODE REVIEW

**Comment by vittring** [comment]
Good catch! Thanks.

**Review by vittring — APPROVED** [review]

**Comment by AnonyPla** [comment]
Note that this could be automated using variables but then "the first jekyll build" will keep the old version. A new subsequent build will be required to update the version automatically.

So: 

- Sollution A: update that file manually (what I did)
- Solution B: update automatically and force a jekyll rebuild after any commit changing the version (even if there is no change), and I'm not sure how to that but it would be ideal

**Comment by AnonyPla** [comment]
Maybe others can have a better solution than manually doing it

**Comment by vittring** [comment]
Environment variables, then you'd only need to change the variable one time in the settings, and it will propagate that version every time.

**Pull request merged**
